version: '3.8'

services:
  fastapi:
    build:
      context: ./FastAPI
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - anima-network

  streamlit:
    build:
      context: ./Streamlit
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    networks:
      - anima-network
    depends_on:
      - fastapi

networks:
  anima-network:
    driver: bridge
